name: Ansible-Role-Nextcloud CI Testing

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        molecule_distro: [ centos-7, centos-8, debian-9, debian-10, ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: inmotionhosting/ansible-role-apache
          path: ./ansible-role-apache
      - uses: actions/checkout@v2
        with:
          repository: inmotionhosting/ansible-role-postgresql
          path: ./ansible-role-postgresql
      - uses: actions/checkout@v2
        with:
          repository: inmotionhosting/ansible-role-php_fpm
          path: ./ansible-role-php_fpm
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Pip install Repo Requirements
        run: pip install -r requirements.txt
      - name: Molecule Test
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}